# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

at <- function(m, G) {
    .Call(`_phenoDLM_at`, m, G)
}

Rt <- function(G, C, W) {
    .Call(`_phenoDLM_Rt`, G, C, W)
}

ft <- function(F, a) {
    .Call(`_phenoDLM_ft`, F, a)
}

Qt <- function(F, R, V) {
    .Call(`_phenoDLM_Qt`, F, R, V)
}

mt <- function(Y, F, a, R, f, Q) {
    .Call(`_phenoDLM_mt`, Y, F, a, R, f, Q)
}

Ct <- function(F, R, Q) {
    .Call(`_phenoDLM_Ct`, F, R, Q)
}

ht <- function(G, C, R, theta, a, m) {
    .Call(`_phenoDLM_ht`, G, C, R, theta, a, m)
}

Ht <- function(C, G, R) {
    .Call(`_phenoDLM_Ht`, C, G, R)
}

ht2 <- function(G, C, W, theta, H, m) {
    .Call(`_phenoDLM_ht2`, G, C, W, theta, H, m)
}

Ht2 <- function(C, G, W) {
    .Call(`_phenoDLM_Ht2`, C, G, W)
}

mvrnormChol <- function(n, mu, sigma) {
    .Call(`_phenoDLM_mvrnormChol`, n, mu, sigma)
}

mvrnormSVD <- function(n, mu, sigma) {
    .Call(`_phenoDLM_mvrnormSVD`, n, mu, sigma)
}

normden <- function(x, mu, sd) {
    .Call(`_phenoDLM_normden`, x, mu, sd)
}

KalmanFilter <- function(Y, V, W, model) {
    .Call(`_phenoDLM_KalmanFilter`, Y, V, W, model)
}

FFBS <- function(G, W, Kalman, SVD = FALSE) {
    .Call(`_phenoDLM_FFBS`, G, W, Kalman, SVD)
}

calc_SSE_error <- function(y, theta, F) {
    .Call(`_phenoDLM_calc_SSE_error`, y, theta, F)
}

calc_SSE_theta <- function(theta, G) {
    .Call(`_phenoDLM_calc_SSE_theta`, theta, G)
}

cauchy_MH <- function(par_current, shape, rate, c) {
    .Call(`_phenoDLM_cauchy_MH`, par_current, shape, rate, c)
}

mcmc_seas_IG_NA <- function(n_reps, dat, initial_values, c, model, T_star, svd = FALSE, save_theta = TRUE) {
    .Call(`_phenoDLM_mcmc_seas_IG_NA`, n_reps, dat, initial_values, c, model, T_star, svd, save_theta)
}

mcmc_local_seas_NA <- function(n_reps, dat, initial_values, prior, model, T_star, svd = FALSE) {
    .Call(`_phenoDLM_mcmc_local_seas_NA`, n_reps, dat, initial_values, prior, model, T_star, svd)
}

inflection_cpp <- function(y) {
    .Call(`_phenoDLM_inflection_cpp`, y)
}

armaWhichMin <- function(x) {
    .Call(`_phenoDLM_armaWhichMin`, x)
}

armaWhichMax <- function(x) {
    .Call(`_phenoDLM_armaWhichMax`, x)
}

remove_sos_new <- function(pog_dat, sos_dat) {
    .Call(`_phenoDLM_remove_sos_new`, pog_dat, sos_dat)
}

remove_pog_new <- function(sos_dat, pog_dat) {
    .Call(`_phenoDLM_remove_pog_new`, sos_dat, pog_dat)
}

merge_df2 <- function(sos_dat, pog_dat) {
    .Call(`_phenoDLM_merge_df2`, sos_dat, pog_dat)
}

checkd_min_new <- function(dat, type, d) {
    .Call(`_phenoDLM_checkd_min_new`, dat, type, d)
}

checkd_max_new <- function(dat, type, d) {
    .Call(`_phenoDLM_checkd_max_new`, dat, type, d)
}

checkd_max_alt <- function(dat, type, d) {
    .Call(`_phenoDLM_checkd_max_alt`, dat, type, d)
}

check_2sos <- function(df, type, cf) {
    .Call(`_phenoDLM_check_2sos`, df, type, cf)
}

check_2pog <- function(df, type, cf) {
    .Call(`_phenoDLM_check_2pog`, df, type, cf)
}

check_2up <- function(df, type, y, cf) {
    .Call(`_phenoDLM_check_2up`, df, type, y, cf)
}

rule_cpp_no_errors <- function(y, cf, d, s) {
    .Call(`_phenoDLM_rule_cpp_no_errors`, y, cf, d, s)
}

add_year_cpp_fixed <- function(rule_out, shift, year_start, year_end, s) {
    .Call(`_phenoDLM_add_year_cpp_fixed`, rule_out, shift, year_start, year_end, s)
}

seas_per_year_cpp <- function(years, type, year_start, year_end) {
    .Call(`_phenoDLM_seas_per_year_cpp`, years, type, year_start, year_end)
}

quantile2 <- function(x, q, upper = FALSE) {
    .Call(`_phenoDLM_quantile2`, x, q, upper)
}

seas_per_year_all_fixed <- function(pts, n_iter, year_start, year_end, cut) {
    .Call(`_phenoDLM_seas_per_year_all_fixed`, pts, n_iter, year_start, year_end, cut)
}

pts_to_intervals_cpp_fixed <- function(pts, seas_output, year_start, year_end, alpha) {
    .Call(`_phenoDLM_pts_to_intervals_cpp_fixed`, pts, seas_output, year_start, year_end, alpha)
}

rule_to_intervals_cpp_fixed <- function(pts, n_iter, year_start, year_end, cut, alpha) {
    .Call(`_phenoDLM_rule_to_intervals_cpp_fixed`, pts, n_iter, year_start, year_end, cut, alpha)
}

mcmc_to_intervals_cpp_fixed <- function(St, cf, d, shift, s, year_start, year_end, cut, alpha, return_points = FALSE) {
    .Call(`_phenoDLM_mcmc_to_intervals_cpp_fixed`, St, cf, d, shift, s, year_start, year_end, cut, alpha, return_points)
}

